cjdutoit/Glory2Him.Api

G2H.Api.Web/Brokers/Storages/StorageBroker.Posts.References.cs
=> BROKERS: Posts

G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.cs, G2H.Api.Web/G2H.Api.Web.csproj, G2H.Api.Web/Models/Posts/Exceptions/AlreadyExistsPostException.cs, G2H.Api.Web/Models/Posts/Exceptions/FailedPostServiceException.cs, G2H.Api.Web/Models/Posts/Exceptions/FailedPostStorageException.cs, G2H.Api.Web/Models/Posts/Exceptions/InvalidPostException.cs, G2H.Api.Web/Models/Posts/Exceptions/InvalidPostReferenceException.cs, G2H.Api.Web/Models/Posts/Exceptions/NullPostException.cs, G2H.Api.Web/Models/Posts/Exceptions/PostDependencyException.cs, G2H.Api.Web/Models/Posts/Exceptions/PostDependencyValidationException.cs, G2H.Api.Web/Models/Posts/Exceptions/PostServiceException.cs, G2H.Api.Web/Models/Posts/Exceptions/PostValidationException.cs, G2H.Api.Web/Models/Posts/Post.cs, G2H.Api.Web/Services/Foundations/Posts/IPostService.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.Validations.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.cs
=> FOUNDATIONS: Add Post Comment

G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.cs, G2H.Api.Web/Services/Foundations/Posts/IPostService.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.cs
=> FOUNDATIONS: Retrieve All Posts 

G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.RetrieveById.cs, G2H.Api.Web/Models/Posts/Exceptions/NotFoundPostException.cs, G2H.Api.Web/Services/Foundations/Posts/IPostService.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.Validations.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.cs
=> FOUNDATIONS: Retrieve Post By Id 

G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.cs, G2H.Api.Web/Services/Foundations/Posts/IPostService.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.Validations.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.cs
=> FOUNDATIONS: Modify Post

G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.RemoveById.cs, G2H.Api.Web/Services/Foundations/Posts/IPostService.cs, G2H.Api.Web/Services/Foundations/Posts/PostService.cs
=> FOUNDATIONS: Remove Post

G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Exceptions.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Logic.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.cs, G2H.Api.Web/Models/Reactions/Exceptions/ReactionServiceException.cs, G2H.Api.Web/Services/Foundations/Reactions/IReactionService.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.cs
=> FOUNDATIONS: Retrieve All Reactions

G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Exceptions.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Logic.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Validations.RetrieveById.cs, G2H.Api.Web/Brokers/Storages/IStorageBroker.Reactions.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.Reactions.cs, G2H.Api.Web/Models/Reactions/Exceptions/NotFoundReactionException.cs, G2H.Api.Web/Services/Foundations/Reactions/IReactionService.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.Validations.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.cs
=> FOUNDATIONS: Retrieve Reaction By Id

G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Exceptions.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Logic.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Validations.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.cs, G2H.Api.Web/Models/Reactions/Exceptions/LockedReactionException.cs, G2H.Api.Web/Services/Foundations/Reactions/IReactionService.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.Validations.cs, G2H.Api.Web/Services/Foundations/Reactions/ReactionService.cs
=> FOUNDATIONS: Modify Reaction

G2H.Api.Web/Brokers/Storages/IStorageBroker.Statuses.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.Statuses.cs, G2H.Api.Web/G2H.Api.Web.csproj
=> BROKERS: Insert Status

G2H.Api.Web/Brokers/Storages/IStorageBroker.Statuses.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.Statuses.cs
=> BROKERS: Select All Statuses

G2H.Api.Web/Brokers/Storages/IStorageBroker.Statuses.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.Statuses.cs
=> BROKERS: Select Status By Id

G2H.Api.Web/Brokers/Storages/IStorageBroker.Statuses.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.Statuses.cs
=> BROKERS: Update Status

G2H.Api.Web/Brokers/Storages/IStorageBroker.Statuses.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.Statuses.cs
=> BROKERS: Delete Status

G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Logic.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Validations.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.cs, G2H.Api.Web/G2H.Api.Web.csproj, G2H.Api.Web/Models/Statuses/Exceptions/AlreadyExistsStatusException.cs, G2H.Api.Web/Models/Statuses/Exceptions/FailedStatusServiceException.cs, G2H.Api.Web/Models/Statuses/Exceptions/FailedStatusStorageException.cs, G2H.Api.Web/Models/Statuses/Exceptions/InvalidStatusException.cs, G2H.Api.Web/Models/Statuses/Exceptions/NullStatusException.cs, G2H.Api.Web/Models/Statuses/Exceptions/StatusDependencyException.cs, G2H.Api.Web/Models/Statuses/Exceptions/StatusDependencyValidationException.cs, G2H.Api.Web/Models/Statuses/Exceptions/StatusServiceException.cs, G2H.Api.Web/Models/Statuses/Exceptions/StatusValidationException.cs, G2H.Api.Web/Services/Foundations/Statuses/IStatusService.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.Validations.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.cs
=> FOUNDATIONS: Add Status

G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Exceptions.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Logic.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.cs, G2H.Api.Web/Services/Foundations/Statuses/IStatusService.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.cs
=> FOUNDATIONS: Retrieve All Status

G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Exceptions.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Logic.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Validations.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.cs, G2H.Api.Web/Models/Statuses/Exceptions/LockedStatusException.cs, G2H.Api.Web/Services/Foundations/Statuses/IStatusService.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.Validations.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.cs
=> FOUNDATIONS: Modify Status

G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Exceptions.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Logic.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Validations.RemoveById.cs, G2H.Api.Web/Services/Foundations/Statuses/IStatusService.cs, G2H.Api.Web/Services/Foundations/Statuses/StatusService.cs
=> FOUNDATIONS: Remove Status

G2H.Api.Web/Brokers/Storages/IStorageBroker.PostTypes.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.PostTypes.cs
=> BROKERS: Insert Post Type

G2H.Api.Web/Brokers/Storages/IStorageBroker.PostTypes.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.PostTypes.cs
=> BROKERS: Select All Post Types

G2H.Api.Web/Brokers/Storages/IStorageBroker.PostTypes.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.PostTypes.cs
=> BROKERS: Select Post Type By Id

G2H.Api.Web/Brokers/Storages/IStorageBroker.PostTypes.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.PostTypes.cs
=> BROKERS: Update Post Type

G2H.Api.Web/Brokers/Storages/IStorageBroker.PostTypes.cs, G2H.Api.Web/Brokers/Storages/StorageBroker.PostTypes.cs
=> BROKERS: Update Post Delete

G2H.Api.Web/Controllers/StatusesController.cs, G2H.Api.Web/G2H.Api.Web.csproj, G2H.Api.Web/Startup.cs
=> CONTROLLERS: GET All Statuses 

G2H.Api.Web/Controllers/StatusesController.cs
=> CONTROLLERS: GET Status By Id

G2H.Api.Web.Tests.Acceptance/Apis/Statuses/StatusesApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Statuses/StatusesApiTests.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.Statuses.cs, G2H.Api.Web/Controllers/ReactionsController.cs, G2H.Api.Web/Models/Reactions/Reaction.cs
=> ACCEPTANCE: Should Get Status

G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.Reactions.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.cs, G2H.Api.Web.Tests.Acceptance/Models/Reactions/Reaction.cs, G2H.Api.Web.Tests.Acceptance/Models/Reactions/ReactionId.cs
=> ACCEPTANCE: Should Get All Reactions

G2H.Api.Web/Controllers/ReactionsController.cs
=> CONTROLLERS: GET Reaction By Id

G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.Reactions.cs
=> ACCEPTANCE: Should Get Reaction By Id

G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Exceptions.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Logic.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.cs, G2H.Api.Web/Services/Foundations/PostTypes/IPostTypeService.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.Exceptions.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.cs
=> FOUNDATIONS: Retrieve All Post Types

G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Exceptions.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Logic.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Validations.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.cs, G2H.Api.Web/Models/PostTypes/Exceptions/NotFoundPostTypeException.cs, G2H.Api.Web/Services/Foundations/PostTypes/IPostTypeService.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.Exceptions.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.Validations.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.cs
=> FOUNDATIONS: Retrieve Post Type By Id

G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Exceptions.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Logic.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Validations.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.cs, G2H.Api.Web/Models/PostTypes/Exceptions/LockedPostTypeException.cs, G2H.Api.Web/Services/Foundations/PostTypes/IPostTypeService.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.Exceptions.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.Validations.cs, G2H.Api.Web/Services/Foundations/PostTypes/PostTypeService.cs
=> FOUNDATIONS: Modify Post Type

G2H.Api.Web/Controllers/PostTypesController.cs, G2H.Api.Web/Startup.cs
=> CONTROLLERS: GET All Post Types

G2H.Api.Web.Tests.Acceptance/Apis/PostTypes/PostTypesApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/PostTypes/PostTypesApiTests.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.PostTypes.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.cs, G2H.Api.Web.Tests.Acceptance/Models/PostTypes/PostType.cs, G2H.Api.Web.Tests.Acceptance/Models/PostTypes/PostTypeId.cs
=> ACCEPTANCE: GET All Post Types

G2H.Api.Web/Controllers/PostTypesController.cs
=> CONTROLLERS: GET Post Type By Id

G2H.Api.Web.Tests.Acceptance/Apis/PostTypes/PostTypesApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/PostTypes/PostTypesApiTests.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.PostTypes.cs
=> ACCEPTANCE: GET Post Type By Id

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Logic.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Validations.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.cs, G2H.Api.Web/Migrations/20220110130824_ApprovalRemovedVersioning.Designer.cs, G2H.Api.Web/Migrations/20220110130824_ApprovalRemovedVersioning.cs, G2H.Api.Web/Models/Approvals/Approval.cs, G2H.Api.Web/Models/Approvals/Exceptions/AlreadyExistsApprovalException.cs, G2H.Api.Web/Models/Approvals/Exceptions/ApprovalDependencyException.cs, G2H.Api.Web/Models/Approvals/Exceptions/ApprovalDependencyValidationException.cs, G2H.Api.Web/Models/Approvals/Exceptions/ApprovalServiceException.cs, G2H.Api.Web/Models/Approvals/Exceptions/ApprovalValidationException.cs, G2H.Api.Web/Models/Approvals/Exceptions/FailedApprovalServiceException.cs, G2H.Api.Web/Models/Approvals/Exceptions/FailedApprovalStorageException.cs, G2H.Api.Web/Models/Approvals/Exceptions/InvalidApprovalException.cs, G2H.Api.Web/Models/Approvals/Exceptions/InvalidApprovalReferenceException.cs, G2H.Api.Web/Models/Approvals/Exceptions/NullApprovalException.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.Validations.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.cs, G2H.Api.Web/Services/Foundations/Approvals/IApprovalService.cs
=> FOUNDATIONS: Add Approval

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Logic.RetrieveAll.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.cs, G2H.Api.Web/Services/Foundations/Approvals/IApprovalService.cs
=> FOUNDATIONS: Retrieve All Approvals

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Logic.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Validations.RetrieveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/NotFoundApprovalException.cs, G2H.Api.Web/Models/Approvals/Exceptions/NotFoundApprovalException.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.Validations.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.cs, G2H.Api.Web/Services/Foundations/Approvals/IApprovalService.cs
=> FOUNDATIONS: Retrieve Approval By Id

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Logic.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Validations.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.cs, G2H.Api.Web/Models/Approvals/Exceptions/LockedApprovalException.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.Exceptions.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.Validations.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.cs, G2H.Api.Web/Services/Foundations/Approvals/IApprovalService.cs
=> FOUNDATIONS: Modify Approval

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Logic.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Validations.RemoveById.cs, G2H.Api.Web/Services/Foundations/Approvals/ApprovalService.cs, G2H.Api.Web/Services/Foundations/Approvals/IApprovalService.cs
=> FOUNDATIONS: Remove Approval By Id

G2H.Api.Web/Controllers/ApprovalsController.cs, G2H.Api.Web/Startup.cs
=> CONTROLLERS: POST Approval

G2H.Api.Web/Controllers/ApprovalsController.cs
=> CONTROLLERS: GET All Approvals

G2H.Api.Web/Controllers/ApprovalsController.cs
=> CONTROLLERS: GET Approval By Id

G2H.Api.Web/Controllers/ApprovalsController.cs
=> CONTROLLERS: PUT Approval

G2H.Api.Web/Controllers/ApprovalsController.cs
=> CONTROLLERS: DELETE Approval

G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.Approvals.cs, G2H.Api.Web.Tests.Acceptance/Models/Approvals/Approval.cs
=> ACCEPTANCE: Should Post Approval

G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.cs
=> ACCEPTANCE: Should Get All Approval

G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.Logic.cs
=> ACCEPTANCE: Should Get Approval By Id

G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.cs
=> ACCEPTANCE: Should Put Approval

G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.Logic.cs
=> ACCEPTANCE: Should Delete Approval

G2H.Api.Web/Controllers/PostsController.cs
=> CONTROLLERS: POST Post

G2H.Api.Web/Controllers/PostsController.cs
=> CONTROLLERS: GET All Post

G2H.Api.Web/Controllers/PostsController.cs
=> CONTROLLERS: GET Post By Id

G2H.Api.Web/Controllers/PostsController.cs
=> CONTROLLERS: PUT Post

G2H.Api.Web/Controllers/PostsController.cs
=> CONTROLLERS: DELETE Post

G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.cs, G2H.Api.Web.Tests.Acceptance/Brokers/ApiBroker.Posts.cs, G2H.Api.Web.Tests.Acceptance/Models/Posts/Post.cs
=> ACCEPTANCE: Should Post Post

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Exceptions.RemoveById.cs
=> CODE RUB:  Fixed Unit Test Method Naming To Match Convention

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.Modify.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.Modify.cs
=> CODE RUB:  Add Explicit Check To Verify Broker Is Never Called

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.Modify.cs
=> CODE RUB: Correct Variable Name

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.RemoveById.cs
=> MINOR FIX: Addition of Missing Sql Exception Test

G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/PostTypes/PostTypeServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RemoveById.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Reactions/ReactionServiceTests.Exceptions.Add.cs, G2H.Api.Web.Tests.Unit/Services/Foundations/Statuses/StatusServiceTests.Exceptions.Add.cs
=> CODE RUB: Fixed Test Names

G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.cs
=> ACCEPTANCE: Should Get All Post

G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.cs
=> ACCEPTANCE: Should Get Post By Id

G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.cs
=> ACCEPTANCE: Should Put Post

G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Posts/PostsApiTests.cs
=> ACCEPTANCE: Should Delete Post

G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.Logic.cs, G2H.Api.Web.Tests.Acceptance/Apis/Approvals/ApprovalsApiTests.cs
=> CODE RUB: Method Name Changed 

.github/workflows/dotnet.yml, G2H.Api.Infrastructure.Build/Program.cs
=> CONFIG: Update .NET Version to 6.0.101

G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.cs
Simplify namespace reference: >> Added the respective library 
Explicit left-hand side: The datatype has been specified 
this qualifier: qualifier added
Implicit left-hand side: "var" datatype has been used
Remove extra line: extra line removed.
=> CODE RUB: Code Cleanup ReactionsApiTests.cs #334
